version: "3"

networks:
  ocrapp:   

services:
  jamspell:
    build: './jam_spell'
    image: morgachev/jamspell
    networks:
      - ocrapp
    depends_on:
      - rabbit
    command: bash -c "
      /wait 
      && python server.py"
    environment:
      WAIT_HOSTS: rabbit:5672

  tesseractocr:
    build: './tesseract_ocr'
    image: morgachev/tessetact
    networks:
      - ocrapp
    depends_on:
      - rabbit
    command: bash -c "
      /wait 
      && python server.py"
    environment:
      WAIT_HOSTS: rabbit:5672
    
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672 
    networks:
      - ocrapp
    container_name: rabbit

  mongo:
    image: mongo
    ports: 
      - 27017:27017
    networks:
      - ocrapp
    restart: always
    container_name: db





