version: "3.7"

networks:
  ocrapp:   

services:
  jamspell:
    build: './jam_spell'
    networks:
      - ocrapp
    depends_on:
      - rabbit
    command: bash -c "
      /wait 
      && python server.py"
    environment:
      WAIT_HOSTS: rabbit:5672

  tesseractocr:
    build: './tesseract_ocr'
    networks:
      - ocrapp
    depends_on:
      - rabbit
    command: bash -c "
      /wait 
      && python server.py"
    environment:
      WAIT_HOSTS: rabbit:5672
    
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672 
    networks:
      - ocrapp
    container_name: rabbit
  




